//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyApp.ServiceCommunication.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.CompServiceSoap")]
    public interface CompServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualTruncate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ManualTruncate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ManualTruncate", ReplyAction="*")]
        System.Threading.Tasks.Task ManualTruncateAsync();
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Download_all_employees) сообщения Download_all_employees не соответствует значению по умолчанию (DownloadAllEmployees).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Download_all_employees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1 DownloadAllEmployees(CompanyApp.ServiceCommunication.CompanyService.Download_all_employees request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Download_all_employees", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1> DownloadAllEmployeesAsync(CompanyApp.ServiceCommunication.CompanyService.Download_all_employees request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Upload_employees) сообщения Upload_employees не соответствует значению по умолчанию (UploadEmployees).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload_employees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Upload_employees1 UploadEmployees(CompanyApp.ServiceCommunication.CompanyService.Upload_employees request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload_employees", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_employees1> UploadEmployeesAsync(CompanyApp.ServiceCommunication.CompanyService.Upload_employees request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Insert_employee) сообщения Insert_employee не соответствует значению по умолчанию (InsertEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_employee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Insert_employee1 InsertEmployee(CompanyApp.ServiceCommunication.CompanyService.Insert_employee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_employee", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_employee1> InsertEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Insert_employee request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Update_employee) сообщения Update_employee не соответствует значению по умолчанию (UpdateEmployee).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_employee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Update_employee1 UpdateEmployee(CompanyApp.ServiceCommunication.CompanyService.Update_employee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_employee", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_employee1> UpdateEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Update_employee request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Download_all_departments) сообщения Download_all_departments не соответствует значению по умолчанию (DownloadAllDepartments).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Download_all_departments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1 DownloadAllDepartments(CompanyApp.ServiceCommunication.CompanyService.Download_all_departments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Download_all_departments", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1> DownloadAllDepartmentsAsync(CompanyApp.ServiceCommunication.CompanyService.Download_all_departments request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Upload_departments) сообщения Upload_departments не соответствует значению по умолчанию (UploadDepartments).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload_departments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Upload_departments1 UploadDepartments(CompanyApp.ServiceCommunication.CompanyService.Upload_departments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload_departments", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_departments1> UploadDepartmentsAsync(CompanyApp.ServiceCommunication.CompanyService.Upload_departments request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Insert_department) сообщения Insert_department не соответствует значению по умолчанию (InsertDepartment).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_department", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Insert_department1 InsertDepartment(CompanyApp.ServiceCommunication.CompanyService.Insert_department request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_department", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_department1> InsertDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Insert_department request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Update_department) сообщения Update_department не соответствует значению по умолчанию (UpdateDepartment).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_department", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Update_department1 UpdateDepartment(CompanyApp.ServiceCommunication.CompanyService.Update_department request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_department", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_department1> UpdateDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Update_department request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (Remove_entry) сообщения Remove_entry не соответствует значению по умолчанию (Remove).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove_entry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CompanyApp.ServiceCommunication.CompanyService.Remove_entry1 Remove(CompanyApp.ServiceCommunication.CompanyService.Remove_entry request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove_entry", ReplyAction="*")]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Remove_entry1> RemoveAsync(CompanyApp.ServiceCommunication.CompanyService.Remove_entry request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : DatabaseEntity {
        
        private string nameField;
        
        private string surnameField;
        
        private string patronymField;
        
        private string birthDateField;
        
        private GenderType genderField;
        
        private char genderAsCharField;
        
        private bool isMaleField;
        
        private bool isFemaleField;
        
        private int salaryField;
        
        private string departmentField;
        
        private string fullNameField;
        
        private string shortNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Patronym {
            get {
                return this.patronymField;
            }
            set {
                this.patronymField = value;
                this.RaisePropertyChanged("Patronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public GenderType Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public char GenderAsChar {
            get {
                return this.genderAsCharField;
            }
            set {
                this.genderAsCharField = value;
                this.RaisePropertyChanged("GenderAsChar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsMale {
            get {
                return this.isMaleField;
            }
            set {
                this.isMaleField = value;
                this.RaisePropertyChanged("IsMale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsFemale {
            get {
                return this.isFemaleField;
            }
            set {
                this.isFemaleField = value;
                this.RaisePropertyChanged("IsFemale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("Salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
                this.RaisePropertyChanged("ShortName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum GenderType {
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class DatabaseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Department : DatabaseEntity {
        
        private string titleField;
        
        private string locationField;
        
        private Employee managerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Employee Manager {
            get {
                return this.managerField;
            }
            set {
                this.managerField = value;
                this.RaisePropertyChanged("Manager");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download_all_employees", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Download_all_employees {
        
        public Download_all_employees() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download_all_employeesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Download_all_employees1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Employee[] Download_all_employeesResult;
        
        public Download_all_employees1() {
        }
        
        public Download_all_employees1(CompanyApp.ServiceCommunication.CompanyService.Employee[] Download_all_employeesResult) {
            this.Download_all_employeesResult = Download_all_employeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_employees", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_employees {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Employee[] list;
        
        public Upload_employees() {
        }
        
        public Upload_employees(CompanyApp.ServiceCommunication.CompanyService.Employee[] list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_employeesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_employees1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Upload_employeesResult;
        
        public Upload_employees1() {
        }
        
        public Upload_employees1(int Upload_employeesResult) {
            this.Upload_employeesResult = Upload_employeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_employee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_employee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Employee entry;
        
        public Insert_employee() {
        }
        
        public Insert_employee(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_employeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_employee1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_employeeResult;
        
        public Insert_employee1() {
        }
        
        public Insert_employee1(int Insert_employeeResult) {
            this.Insert_employeeResult = Insert_employeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_employee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_employee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Employee entry;
        
        public Update_employee() {
        }
        
        public Update_employee(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_employeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_employee1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Update_employeeResult;
        
        public Update_employee1() {
        }
        
        public Update_employee1(int Update_employeeResult) {
            this.Update_employeeResult = Update_employeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download_all_departments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Download_all_departments {
        
        public Download_all_departments() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Download_all_departmentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Download_all_departments1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Department[] Download_all_departmentsResult;
        
        public Download_all_departments1() {
        }
        
        public Download_all_departments1(CompanyApp.ServiceCommunication.CompanyService.Department[] Download_all_departmentsResult) {
            this.Download_all_departmentsResult = Download_all_departmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_departments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_departments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Department[] list;
        
        public Upload_departments() {
        }
        
        public Upload_departments(CompanyApp.ServiceCommunication.CompanyService.Department[] list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload_departmentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Upload_departments1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Upload_departmentsResult;
        
        public Upload_departments1() {
        }
        
        public Upload_departments1(int Upload_departmentsResult) {
            this.Upload_departmentsResult = Upload_departmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_department", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_department {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Department entry;
        
        public Insert_department() {
        }
        
        public Insert_department(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_departmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_department1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_departmentResult;
        
        public Insert_department1() {
        }
        
        public Insert_department1(int Insert_departmentResult) {
            this.Insert_departmentResult = Insert_departmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_department", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_department {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.Department entry;
        
        public Update_department() {
        }
        
        public Update_department(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_departmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Update_department1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Update_departmentResult;
        
        public Update_department1() {
        }
        
        public Update_department1(int Update_departmentResult) {
            this.Update_departmentResult = Update_departmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove_entry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Remove_entry {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CompanyApp.ServiceCommunication.CompanyService.DatabaseEntity entry;
        
        public Remove_entry() {
        }
        
        public Remove_entry(CompanyApp.ServiceCommunication.CompanyService.DatabaseEntity entry) {
            this.entry = entry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove_entryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Remove_entry1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Remove_entryResult;
        
        public Remove_entry1() {
        }
        
        public Remove_entry1(int Remove_entryResult) {
            this.Remove_entryResult = Remove_entryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompServiceSoapChannel : CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompServiceSoapClient : System.ServiceModel.ClientBase<CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap>, CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap {
        
        public CompServiceSoapClient() {
        }
        
        public CompServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ManualTruncate() {
            base.Channel.ManualTruncate();
        }
        
        public System.Threading.Tasks.Task ManualTruncateAsync() {
            return base.Channel.ManualTruncateAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.DownloadAllEmployees(CompanyApp.ServiceCommunication.CompanyService.Download_all_employees request) {
            return base.Channel.DownloadAllEmployees(request);
        }
        
        public CompanyApp.ServiceCommunication.CompanyService.Employee[] DownloadAllEmployees() {
            CompanyApp.ServiceCommunication.CompanyService.Download_all_employees inValue = new CompanyApp.ServiceCommunication.CompanyService.Download_all_employees();
            CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).DownloadAllEmployees(inValue);
            return retVal.Download_all_employeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.DownloadAllEmployeesAsync(CompanyApp.ServiceCommunication.CompanyService.Download_all_employees request) {
            return base.Channel.DownloadAllEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_employees1> DownloadAllEmployeesAsync() {
            CompanyApp.ServiceCommunication.CompanyService.Download_all_employees inValue = new CompanyApp.ServiceCommunication.CompanyService.Download_all_employees();
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).DownloadAllEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Upload_employees1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UploadEmployees(CompanyApp.ServiceCommunication.CompanyService.Upload_employees request) {
            return base.Channel.UploadEmployees(request);
        }
        
        public int UploadEmployees(CompanyApp.ServiceCommunication.CompanyService.Employee[] list) {
            CompanyApp.ServiceCommunication.CompanyService.Upload_employees inValue = new CompanyApp.ServiceCommunication.CompanyService.Upload_employees();
            inValue.list = list;
            CompanyApp.ServiceCommunication.CompanyService.Upload_employees1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UploadEmployees(inValue);
            return retVal.Upload_employeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_employees1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UploadEmployeesAsync(CompanyApp.ServiceCommunication.CompanyService.Upload_employees request) {
            return base.Channel.UploadEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_employees1> UploadEmployeesAsync(CompanyApp.ServiceCommunication.CompanyService.Employee[] list) {
            CompanyApp.ServiceCommunication.CompanyService.Upload_employees inValue = new CompanyApp.ServiceCommunication.CompanyService.Upload_employees();
            inValue.list = list;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UploadEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Insert_employee1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.InsertEmployee(CompanyApp.ServiceCommunication.CompanyService.Insert_employee request) {
            return base.Channel.InsertEmployee(request);
        }
        
        public int InsertEmployee(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            CompanyApp.ServiceCommunication.CompanyService.Insert_employee inValue = new CompanyApp.ServiceCommunication.CompanyService.Insert_employee();
            inValue.entry = entry;
            CompanyApp.ServiceCommunication.CompanyService.Insert_employee1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).InsertEmployee(inValue);
            return retVal.Insert_employeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_employee1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.InsertEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Insert_employee request) {
            return base.Channel.InsertEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_employee1> InsertEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            CompanyApp.ServiceCommunication.CompanyService.Insert_employee inValue = new CompanyApp.ServiceCommunication.CompanyService.Insert_employee();
            inValue.entry = entry;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).InsertEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Update_employee1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UpdateEmployee(CompanyApp.ServiceCommunication.CompanyService.Update_employee request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public int UpdateEmployee(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            CompanyApp.ServiceCommunication.CompanyService.Update_employee inValue = new CompanyApp.ServiceCommunication.CompanyService.Update_employee();
            inValue.entry = entry;
            CompanyApp.ServiceCommunication.CompanyService.Update_employee1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UpdateEmployee(inValue);
            return retVal.Update_employeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_employee1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UpdateEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Update_employee request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_employee1> UpdateEmployeeAsync(CompanyApp.ServiceCommunication.CompanyService.Employee entry) {
            CompanyApp.ServiceCommunication.CompanyService.Update_employee inValue = new CompanyApp.ServiceCommunication.CompanyService.Update_employee();
            inValue.entry = entry;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.DownloadAllDepartments(CompanyApp.ServiceCommunication.CompanyService.Download_all_departments request) {
            return base.Channel.DownloadAllDepartments(request);
        }
        
        public CompanyApp.ServiceCommunication.CompanyService.Department[] DownloadAllDepartments() {
            CompanyApp.ServiceCommunication.CompanyService.Download_all_departments inValue = new CompanyApp.ServiceCommunication.CompanyService.Download_all_departments();
            CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).DownloadAllDepartments(inValue);
            return retVal.Download_all_departmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.DownloadAllDepartmentsAsync(CompanyApp.ServiceCommunication.CompanyService.Download_all_departments request) {
            return base.Channel.DownloadAllDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Download_all_departments1> DownloadAllDepartmentsAsync() {
            CompanyApp.ServiceCommunication.CompanyService.Download_all_departments inValue = new CompanyApp.ServiceCommunication.CompanyService.Download_all_departments();
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).DownloadAllDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Upload_departments1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UploadDepartments(CompanyApp.ServiceCommunication.CompanyService.Upload_departments request) {
            return base.Channel.UploadDepartments(request);
        }
        
        public int UploadDepartments(CompanyApp.ServiceCommunication.CompanyService.Department[] list) {
            CompanyApp.ServiceCommunication.CompanyService.Upload_departments inValue = new CompanyApp.ServiceCommunication.CompanyService.Upload_departments();
            inValue.list = list;
            CompanyApp.ServiceCommunication.CompanyService.Upload_departments1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UploadDepartments(inValue);
            return retVal.Upload_departmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_departments1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UploadDepartmentsAsync(CompanyApp.ServiceCommunication.CompanyService.Upload_departments request) {
            return base.Channel.UploadDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Upload_departments1> UploadDepartmentsAsync(CompanyApp.ServiceCommunication.CompanyService.Department[] list) {
            CompanyApp.ServiceCommunication.CompanyService.Upload_departments inValue = new CompanyApp.ServiceCommunication.CompanyService.Upload_departments();
            inValue.list = list;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UploadDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Insert_department1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.InsertDepartment(CompanyApp.ServiceCommunication.CompanyService.Insert_department request) {
            return base.Channel.InsertDepartment(request);
        }
        
        public int InsertDepartment(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            CompanyApp.ServiceCommunication.CompanyService.Insert_department inValue = new CompanyApp.ServiceCommunication.CompanyService.Insert_department();
            inValue.entry = entry;
            CompanyApp.ServiceCommunication.CompanyService.Insert_department1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).InsertDepartment(inValue);
            return retVal.Insert_departmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_department1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.InsertDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Insert_department request) {
            return base.Channel.InsertDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Insert_department1> InsertDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            CompanyApp.ServiceCommunication.CompanyService.Insert_department inValue = new CompanyApp.ServiceCommunication.CompanyService.Insert_department();
            inValue.entry = entry;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).InsertDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Update_department1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UpdateDepartment(CompanyApp.ServiceCommunication.CompanyService.Update_department request) {
            return base.Channel.UpdateDepartment(request);
        }
        
        public int UpdateDepartment(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            CompanyApp.ServiceCommunication.CompanyService.Update_department inValue = new CompanyApp.ServiceCommunication.CompanyService.Update_department();
            inValue.entry = entry;
            CompanyApp.ServiceCommunication.CompanyService.Update_department1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UpdateDepartment(inValue);
            return retVal.Update_departmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_department1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.UpdateDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Update_department request) {
            return base.Channel.UpdateDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Update_department1> UpdateDepartmentAsync(CompanyApp.ServiceCommunication.CompanyService.Department entry) {
            CompanyApp.ServiceCommunication.CompanyService.Update_department inValue = new CompanyApp.ServiceCommunication.CompanyService.Update_department();
            inValue.entry = entry;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).UpdateDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CompanyApp.ServiceCommunication.CompanyService.Remove_entry1 CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.Remove(CompanyApp.ServiceCommunication.CompanyService.Remove_entry request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(CompanyApp.ServiceCommunication.CompanyService.DatabaseEntity entry) {
            CompanyApp.ServiceCommunication.CompanyService.Remove_entry inValue = new CompanyApp.ServiceCommunication.CompanyService.Remove_entry();
            inValue.entry = entry;
            CompanyApp.ServiceCommunication.CompanyService.Remove_entry1 retVal = ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).Remove(inValue);
            return retVal.Remove_entryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Remove_entry1> CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap.RemoveAsync(CompanyApp.ServiceCommunication.CompanyService.Remove_entry request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyApp.ServiceCommunication.CompanyService.Remove_entry1> RemoveAsync(CompanyApp.ServiceCommunication.CompanyService.DatabaseEntity entry) {
            CompanyApp.ServiceCommunication.CompanyService.Remove_entry inValue = new CompanyApp.ServiceCommunication.CompanyService.Remove_entry();
            inValue.entry = entry;
            return ((CompanyApp.ServiceCommunication.CompanyService.CompServiceSoap)(this)).RemoveAsync(inValue);
        }
    }
}
